from tkinter import *
window = Tk()
window.minsize(400,200)
window.maxsize(400,200)
window.configure(bg = "#3c3f43")
window.title("Colour Picker")
display = Frame(bg = "#ffffff", width = 100, height = 100, highlightbackground = "black", highlightthickness = 2)
display.place(x = 25, y = 25)
r = Entry(width = 4, highlightbackground = "#ff0000", highlightthickness = 2)
g = Entry(width = 4, highlightbackground = "#00ff00", highlightthickness = 2)
b = Entry(width = 4, highlightbackground = "#0000ff", highlightthickness = 2)
r1 = Label(text = "R:", bg = "#3c3f43", fg = "white")
g1 = Label(text = "G:", bg = "#3c3f43", fg = "white")
b1 = Label(text = "B:", bg = "#3c3f43", fg = "white")
r1.place(x = 134, y = 50)
r.place(x = 150, y = 50)
g1.place(x = 184, y = 50)
g.place(x = 200, y = 50)
b1.place(x = 234, y = 50)
b.place(x = 250, y = 50)
h1 = Label(text = "Hex: #", bg = "#3c3f43", fg = "white")
h = Entry(width = 6, highlightbackground = "black", highlightthickness = 2)
h1.place(x = 162.5, y = 120)
h.place(x = 202.5, y = 120)
r.insert(1,"255")
g.insert(1,"255")
b.insert(1,"255")
h.insert(1,"ffffff")
colourlist = Listbox()
colourlist.place(x = 300, width = 100, height = 200)
def displayrgb():
    rnum = int(r.get())
    gnum = int(g.get())
    bnum = int(b.get())
    rnum = "0x{:02x}".format(rnum)
    gnum = "0x{:02x}".format(gnum)
    bnum = "0x{:02x}".format(bnum)
    rnum = rnum.replace("0x","")
    gnum = gnum.replace("0x","")
    bnum = bnum.replace("0x","")
    h.delete(0, END)
    h.insert(1, rnum + gnum + bnum)
    colour = "#" + rnum + gnum + bnum
    display = Frame(bg = colour, width = 100, height = 100, highlightbackground = "black", highlightthickness = 2)
    display.place(x = 25, y = 25)
    colourlist.insert(0,colour)
def displayhex():
    colour = h.get()
    r.delete(0, END)
    g.delete(0, END)
    b.delete(0, END)
    r.insert(1, int(colour[0:2], 16))
    g.insert(1, int(colour[2:4], 16))
    b.insert(1, int(colour[4:6], 16))
    colour = "#" + colour
    display = Frame(bg = colour, width = 100, height = 100, highlightbackground = "black", highlightthickness = 2)
    display.place(x = 25, y = 25)
    colourlist.insert(0,colour)
def resetbutton():
    r.delete(0, END)
    g.delete(0, END)
    b.delete(0, END)
    h.delete(0, END)
    r.insert(1,"255")
    g.insert(1,"255")
    b.insert(1,"255")
    h.insert(1,"ffffff")
    display = Frame(bg = "#ffffff", width = 100, height = 100, highlightbackground = "black", highlightthickness = 2)
    display.place(x = 25, y = 25)
def loadprevious(event):
    w = event.widget
    index = int(w.curselection()[0])
    colour = w.get(index).replace("#","")
    r.delete(0, END)
    g.delete(0, END)
    b.delete(0, END)
    r.insert(1, int(colour[0:2], 16))
    g.insert(1, int(colour[2:4], 16))
    b.insert(1, int(colour[4:6], 16))
    h.delete(0,END)
    h.insert(1,colour)
    colour = "#" + colour
    display = Frame(bg = colour, width = 100, height = 100, highlightbackground = "black", highlightthickness = 2)
    display.place(x = 25, y = 25)
hexd = Button(text = "Display Hex Colour", command = displayhex)
hexd.place(x = 150, y = 150, width = 132.5)
rgb = Button(text = "Display RGB Colour", command = displayrgb)
rgb.place(x = 150, y = 80, width = 132.5)
reset = Button(text = "Reset", command = resetbutton)
reset.place(x = 50, y = 150, width = 50)
window.bind("<<ListboxSelect>>",loadprevious)
window.mainloop()