import time
print("Welcome to the escape room!")
time.sleep(2)
print("You are locked in a storage locker...")
time.sleep(2)
print("There is a keypad to open the door, but you do not know the code.")
time.sleep(2)
print("You do not know how or why you are here, you just know that you need to get out.")
time.sleep(2)
print("At each stage there will be 4 options for you to choose from.")
time.sleep(2)
print("Choose the right path, and it will lead to your freedom.")
time.sleep(2)
print("Press Enter to start.")
input()
time.sleep(2)
print("You look around, and notice there is a desk and computer behind you.")
time.sleep(2)
print("It has drawers on the side, a chair in front of it and random papers littered on top.")
time.sleep(2)
print("You can either:\n1) Turn on the computer\n2) Look through the desk draws\n3) Read the documents on the desk\n4) Roll around on the chair")
print("Type 1, 2, 3 or 4 to chose what to do.")
choice1 = input()
if choice1 == "1":
    time.sleep(2)
    print("You plug in the computer, and it blinks to life. However, to your horror, it is password protcted.")
    time.sleep(2)
    print("It displays a message saying it will self destruct if the wrong password is entered.")
    time.sleep(2)
    print("You need to find the password.")
    time.sleep(2)
    print("You can either:\n1) Try and hack the system\n2) Look through the desk draws\n3) Read the documents on the desk\n4) Give up and sleep on the chair")
    time.sleep(2)
    print("Type 1, 2, 3 or 4 to choose what to do.")
    choice2 = input()
    time.sleep(2)
    if choice2 == "1":
       print("You try and hack the system, but the computer displays this message:")
       time.sleep(2)
       print("'YOU WILL DIE'")
       time.sleep(2)
       print("The computer spirals into a matrix as all hope leaves your body, and the room fills with toxic gas,")
       time.sleep(2)
       count = 0
       while count > -1:
           count += 36983741734865813649837467456758976785672135568142361234785821684588
           print(str(count)+" GAME OVER "+str(count))
    elif choice2 == "2":
        print("You find a stapler, a broken pen, and a post it note with what looks like a password on it: 'JSpringer248'")
        time.sleep(2)
        print("You think it is the password for the computer.")
        time.sleep(2)
        print("You enter it in aaaand...")
        time.sleep(5)
        print("SUCCESS!")
        time.sleep(2)
        print("You use the computer to contact the emergency services and are resuced.")
        time.sleep(2)
        print("A man named 'Jerry Springer' is arrested for your kidnap and attempted murder.")
        time.sleep(2)
        print("You gain your memories back, and go back to living your life as normal...")
        time.sleep(5)
        print("...for now")
        time.sleep(2)
        print("T")
        time.sleep(0.5)
        print("H")
        time.sleep(0.5)
        print("E")
        time.sleep(0.5)
        print(" ")
        time.sleep(0.5)
        print("E")
        time.sleep(0.5)
        print("N")
        time.sleep(0.5)
        print("D")
    elif choice2 == "3":
        print("The documents are some bank statements belonging to a man named 'Jerry Springer'.")
        time.sleep(2)
        print("Using this information, you try and guess the password.")
        time.sleep(5)
        print("However, you guess it wrong, and the computer activates its self destruct sequence.")
        time.sleep(2)
        print("The janitor hears the noise and finds you dead on the floor")
        time.sleep(2)
        print("G")
        time.sleep(0.5)
        print("A")
        time.sleep(0.5)
        print("M")
        time.sleep(0.5)
        print("E")
        time.sleep(0.5)
        print(" ")
        time.sleep(0.5)
        print("O")
        time.sleep(0.5)
        print("V")
        time.sleep(0.5)
        print("E")
        time.sleep(0.5)
        print("R")
    elif choice2 == "4":
        print("You fall into a deep sleep as the room gradually fills with toxic gas.")
        time.sleep(2)
        print("Your body is found by the janitor next moring.")
        time.sleep(2)
        print("G")
        time.sleep(0.5)
        print("A")
        time.sleep(0.5)
        print("M")
        time.sleep(0.5)
        print("E")
        time.sleep(0.5)
        print(" ")
        time.sleep(0.5)
        print("O")
        time.sleep(0.5)
        print("V")
        time.sleep(0.5)
        print("E")
        time.sleep(0.5)
        print("R")
    else:
        print("This is not a valid choice, please reload the game and try again.")
elif choice1 == "2":
    print("You find a stapler, a broken pen, and a post it note with some letters and numbers scribbled on it: 'JSpringer248' and '2387'")
    time.sleep(2)
    print("You think it might be the pass code for the keypad at the door.")
    time.sleep(2)
    print("You try and enter the pass code in aaaand...")
    time.sleep(2)
    print("The lights turn red and a loud voice booms from the speakers:")
    time.sleep(2)
    print("ACTIVATING: SELF DESTRUCT")
    time.sleep(2)
    print("The janitor hears a loud bang and finds you dead on the floor")
    time.sleep(2)
    print("G")
    time.sleep(0.5)
    print("A")
    time.sleep(0.5)
    print("M")
    time.sleep(0.5)
    print("E")
    time.sleep(0.5)
    print(" ")
    time.sleep(0.5)
    print("O")
    time.sleep(0.5)
    print("V")
    time.sleep(0.5)
    print("E")
    time.sleep(0.5)
    print("R")
elif choice1 == "3":
    print("The documents are some bank statements belonging to a man named 'Jerry Springer'.")
    time.sleep(2)
    print("You remember that name from somewhere, and spend some time thinking about it.")
    time.sleep(2)
    print("After some time, you remember that he was your archnemesis.")
    time.sleep(2)
    print("However it is too late and you hear a faint hiss as toxic gas fills the room.")
    time.sleep(2)
    print("Your body is found by the janitor the next morning.")
    time.sleep(2)
    print("G")
    time.sleep(0.5)
    print("A")
    time.sleep(0.5)
    print("M")
    time.sleep(0.5)
    print("E")
    time.sleep(0.5)
    print(" ")
    time.sleep(0.5)
    print("O")
    time.sleep(0.5)
    print("V")
    time.sleep(0.5)
    print("E")
    time.sleep(0.5)
    print("R")
elif choice1 == "4":
    print("You play around on the chair until you go too fast and hit your head on the wall and pass out.")
    time.sleep(2)
    print("Your body is found by the janitor the next morning.")
    time.sleep(2)
    print("G")
    time.sleep(0.5)
    print("A")
    time.sleep(0.5)
    print("M")
    time.sleep(0.5)
    print("E")
    time.sleep(0.5)
    print(" ")
    time.sleep(0.5)
    print("O")
    time.sleep(0.5)
    print("V")
    time.sleep(0.5)
    print("E")
    time.sleep(0.5)
    print("R")
else:
    print("This is not a valid choice, please reload the game and try again.")
input()
