print("Team name:")
name = input()
print("Number of wins:")
wins = int(input())
print("Nmber of draws:")
draws = int(input())
points =(wins*3)+(draws*1)
print("Team name:",name)
print("Number of points:",points)
input()
